[workspace]
members = [
    "weave-common",
    "weave-ntdll",
    "weave-kernel32",
    "weave-advapi32",
    "weave-user32",
    "weave-gdi32",
    "weave-shell32",
    "weave-ole32",
    "weave-sandbox",
    "weave-core",
    "weave-vulkan",
    "weave-cli",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/eldo9000/Weave"
