[workspace]
members = [
    "weave-common",
    "weave-desktop",
    "weave-installer",
    "weave-notify",
    "weave-ntdll",
    "weave-kernel32",
    "weave-advapi32",
    "weave-user32",
    "weave-gdi32",
    "weave-shell32",
    "weave-ole32",
    "weave-sandbox",
    "weave-core",
    "weave-ucrt",
    "weave-vulkan",
    "weave-cli", "weave-mmdevapi", "weave-d3d12", "weave-plugin-system", "weave-xinput", "weave-compat-db", "weave-winmm",
    "weave-ws2",
    "weave-comctl32",
    "weave-oleaut32",
    "weave-imm32",
    "weave-shlwapi",
    "weave-gdiplus",
    "weave-ddraw",
    "weave-msvcp140",
    "weave-setupapi",
    "weave-bcrypt",
    "weave-bcryptprimitives",
    "weave-crypt32",
    "weave-normaliz",
    "weave-secur32",
    "weave-wldap32",
    "weave-dwrite",
    "weave-powrprof",
    "weave-audacity",
]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/The-Libre-Project/Weave"
