[package]
name = "weave-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Command-line interface for Weave"

[[bin]]
name = "weave"
path = "src/main.rs"

[dependencies]
weave-core = { path = "../weave-core" }
weave-ntdll = { path = "../weave-ntdll" }
weave-kernel32 = { path = "../weave-kernel32" }
weave-advapi32 = { path = "../weave-advapi32" }
weave-user32 = { path = "../weave-user32" }
weave-gdi32 = { path = "../weave-gdi32" }
weave-shell32 = { path = "../weave-shell32" }
weave-ole32 = { path = "../weave-ole32" }
weave-mmdevapi = { path = "../weave-mmdevapi" }
weave-xinput = { path = "../weave-xinput" }
weave-winmm = { path = "../weave-winmm" }
weave-plugin-system = { path = "../weave-plugin-system" }
weave-vm-fallback = { path = "../weave-vm-fallback" }
weave-ucrt = { path = "../weave-ucrt" }
weave-vulkan = { path = "../weave-vulkan" }
weave-ws2 = { path = "../weave-ws2" }
weave-comctl32 = { path = "../weave-comctl32" }
weave-oleaut32 = { path = "../weave-oleaut32" }
weave-imm32 = { path = "../weave-imm32" }
weave-shlwapi = { path = "../weave-shlwapi" }
weave-gdiplus = { path = "../weave-gdiplus" }
weave-ddraw = { path = "../weave-ddraw" }
weave-sandbox = { path = "../weave-sandbox" }
weave-installer = { path = "../weave-installer" }
weave-common = { path = "../weave-common" }
weave-desktop = { path = "../weave-desktop" }
clap = { version = "4", features = ["derive"] }
libc = "0.2"

[dev-dependencies]
tempfile = "3"
