[package]
name = "weave-advapi32"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "advapi32.dll stubs for Weave — registry, security, and services"

[dependencies]
libc = "0.2"
weave-common = { path = "../weave-common" }
weave-core = { path = "../weave-core" }
weave-kernel32 = { path = "../weave-kernel32" }
