#!/usr/bin/env bash
# gen-msvcp140-stubs.sh — Generate bulk MSVCP140 no-op stub entries.
#
# Usage:
#   1. Run the audacity probe with WEAVE_IAT_TRACE=1:
#        WEAVE_IAT_TRACE=1 cargo test -p weave-cli --test hello_world \
#          audacity_phase_a_probe -- --nocapture 2>&1 | tee /tmp/probe.out
#   2. Run this script on the output:
#        bash scripts/gen-msvcp140-stubs.sh /tmp/probe.out
#
# The script extracts all "unresolved import: MSVCP140.dll!<name>"
# lines, deduplicates them, and outputs ready-to-paste | -separated
# entries for the msvcp_noop section in weave-msvcp140/src/lib.rs.
set -euo pipefail

INPUT="${1:-/dev/stdin}"

# Check if the input file exists
if [ ! -f "$INPUT" ] && [ "$INPUT" != "/dev/stdin" ]; then
    echo "Error: input file '$INPUT' not found"
    echo "Usage: $0 [probe-output-file]"
    exit 1
fi

echo "// AUTO-GENERATED by scripts/gen-msvcp140-stubs.sh"
echo "// Run date: $(date -u '+%Y-%m-%d %H:%M UTC')"
echo "// Source: $INPUT"
echo ""

# Extract MSVCP140 unresolved imports (both "stubbed to null" and "skipped").
# Also extract VCRUNTIME140 and VCRUNTIME140_1 stubs.
for DLL in MSVCP140 VCRUNTIME140 VCRUNTIME140_1; do
    SYMBOLS=$(grep -oP "${DLL}\.dll!\K[^ ]+(?= at iat)" "$INPUT" | sed 's/ (skipped)//' | sort -u)
    COUNT=$(echo "$SYMBOLS" | grep -c . || true)
    
    if [ "$COUNT" -eq 0 ]; then
        continue
    fi
    
    echo "// ── ${DLL}.dll (${COUNT} stubs) ─────────────────────────────────────"
    echo ""
    
    # Filter out symbols that already exist in the resolve map by checking a
    # pre-defined list of already-handled patterns.
    FIRST=true
    while IFS= read -r sym; do
        # Skip empty lines
        [ -z "$sym" ] && continue
        
        # Escape for Rust string literal (pipe symbols are fine in | alternation)
        escaped_sym=$(echo "$sym" | sed 's/|/\\|/g')
        
        if [ "$FIRST" = true ]; then
            echo "        \"$escaped_sym\""
            FIRST=false
        else
            echo "        | \"$escaped_sym\""
        fi
    done <<< "$SYMBOLS"
    
    echo "        => msvcp_noop as *const () as usize,"
    echo ""
done

echo "// ── Instructions ──────────────────────────────────────────────────"
echo "// 1. Open weave-msvcp140/src/lib.rs"
echo "// 2. Find the msvcp_noop alternation block (ends with '=> msvcp_noop as *const () as usize,')"
echo "// 3. Insert the MSVCP140.dll entries above the existing ones"
echo "// 4. For VCRUNTIME140/140_1 entries, add to weave-audacity/src/lib.rs resolve() instead"
echo "// 5. Run: cargo check -p weave-msvcp140"
echo "// 6. Re-run probe to verify reduction in unresolved count"
